### ISSUE TITLE
Recommendations for abbreviations 

### ISSUE THREAD

**Issue by bradleyryanbtc** [BitcoinDesign/Guide#907] opened 2022-09-07 14:48 UTC
**Describe your content request**

Hello, I would like to request a recommendation on how to abbreviate addresses. 

First 4 ... Last 4
First 8 ... Last 4
etc

How are different address types abbreviated? 

**Link to the page**
[_Link_
](https://bitcoin.design/guide/daily-spending-wallet/activity/)

**Additional context**
<img width="291" alt="Screen Shot 2022-09-07 at 8 42 10 AM" src="https://user-images.githubusercontent.com/57381091/188907001-d5d97f8c-0a90-446c-a2c7-2e9115217642.png">
<img width="170" alt="Screen Shot 2022-09-07 at 8 44 01 AM" src="https://user-images.githubusercontent.com/57381091/188907430-10f4e89f-9db5-445c-aa75-3621895120c6.png">
<img width="308" alt="Screen Shot 2022-09-07 at 8 44 21 AM" src="https://user-images.githubusercontent.com/57381091/188907512-2af2072b-459b-4418-842e-0ac108d47e19.png">

**Comment by GBKS** [comment] 2022-09-09 08:34
Thanks for opening the issue, Bradley. On the [addresses page](https://bitcoin.design/guide/glossary/address/), you'll see the format `XXXX XXXX ... XXXX` used. That's because Taproot addresses start with `bc1p` (others types start with `1`, `3`, and `bc1q`). This makes those first 1 or 4 characters useless for identifying specific addresses. If you wanted to, you could use `XXXX ... XXXX` for legacy and script addresses (like in the images above) and have two different formats based on address type. But considering those are "outdated", I think the `XXXX XXXX ... XXXX` format is pretty good default to go with. It's short enough to fit on mobile, and still allows users to roughly identify specific addresses (for exact identification, they should be able to quickly access the full address anyways).

What is your thinking on this design problem?

**Comment by Bosch-0** [comment] 2022-10-01 02:10
Yeah the XXXX (address type), XXXX ... XXXX should cover enough characters (8) that majority of the time verifying those should be suffice in prevent a malware attack. Four characters is also what credit cards use which people are familiar with verifying. 

Here is some UX research on chunking data like this and why it's useful: https://www.nngroup.com/articles/chunking/ 

I'll add it's also important to make the full address (when shown) use some form of chunking to make it easier to verify address content. See example below

bc1p mzfr wwnd sqmk 5yh6 9yjr 5lfg fg4e v8c0 tsc0 6e

**Comment by GBKS** [comment] 2022-10-03 07:51
Chunking of addresses is also illustrated in the guide [here](https://bitcoin.design/guide/glossary/address/#visual-formatting).

Was just being annoyed by this last Friday while trying to ensure addresses matched between hardware wallet and smartphone app. That little bit of space, and some slightly alternating colors make it so much easier to compare.

**Comment by pavlenex** [comment] 2022-11-22 11:12
Duplicate of the #849
We do have it here https://bitcoin.design/guide/glossary/address/#visual-formatting
If you'd like to have some more content around it let us know where and we can revisit and reopend this issue.

**Closed by pavlenex** 2022-11-22 11:12 UTC
Labels: Design
