### ISSUE TITLE
Create a page for design collaboration and shared design resources

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#35] opened 2020-10-19 11:17 UTC
I think a page like this could help us with two things.

First, it looks like we will be using Figma for many designs due to the ease of sharing and collaboration. While Github has many pre-defined processes built-in, Figma and other design tools do not. So I think it would be helpful if we articulate these for us.

Second, there are a few design resources being worked on that we will make publicly available for anyone to use and contribute to. Currently we have many Figma links floating around with no way to find them again other than asking around or searching Slack/Figma history. We can also list important design resources on this page.

This page would likely be under "Resources".

Below is a mock-up with some quickly written copy. What do you think of this? Note that this is heavily slanted towards collaborating on Figma community files. So this might need to be a sub-page under a more general "Design collaboration" or "Open design" section that is tool-agnostic.

<img width="1440" alt="Design collaboration page 201019" src="https://user-images.githubusercontent.com/695901/96443633-364fb400-120d-11eb-8597-2d488658d9cc.png">

**Comment by pavlenex** [comment] 2020-10-19 15:58
Don't have any concrete feedback to add, except that I really like the idea of having all of these at a single page. Navigating through Figma is not always easy, so if it means anything, I find this kind of page quite helpful.

**Comment by pavlenex** [comment] 2020-10-23 09:04
@GBKS and I were discussing the dev-designer workflow around a specific issue we have on @btcpayserver so I documneted the typical process. Of course, in a fast-paced environment things don't always go in a pattern like this, but  this is quite typical flow.

## BTCPay Dev/Designer collaboration on an issue

The goal of this document is to quickly describe the workflow of the designer and dev community when tackling a particular UX/UI related issue.

* **User** reports a problem usually on our community chat
* If the issue is significant or repeats in the past a **new issue** is opened
* In the issue, we tend to describe the specific problem, why it happens and how it can be solved
* The issue is presented at a **core team meeting** and then included into a sprint (we do 2-3 week sprints and release a new version).
* Then the issue is presented at a **designer meeting**. Where usually a dev is present so that we’re sure sketches and ideas are technically possible in the time-frame.
* Once the issue is in designers hands, designers then create multiple **iterations on Figma** of and present them via our UX/UI channel for more feedback.
* Once there’s a good enough iteration, it’s **presented** on the original issue on **GitHub**
* The design is then reviewed by maintainers where usually additional feedback is passed along.
*Designer then goes **back to Figma** and creates a few more iterations, showing them to the community in the UX/UI channel and passing them to the issue.
* Once the mockup is satisfactory, then the **dev team** takes over the issues 
* Dev in charge creates **a pull request**
* **Tester** team then tests a PR in a local environment, presents screenshots and points out potential problems.
* Designers are pinged in the UX/UI channel or on GitHub in case there’s a solution that differs from their proposed design.
* Once the pull requests passes designer and testers review, **code reviewer** takes a look at the code (the specific time when a code is reviewed differs) 
* Once both tester and code reviewers approve the PR, the pull request is then **merged** (provided that there’s a consensus from maintainers)

**Comment by ConorOkus** [comment] 2021-06-25 17:56
Ship it!

**Closed** 2021-07-07 15:27 UTC
Labels: copy, dev
