### ISSUE TITLE
Ensure all pages link to the next page or chapter

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#386] opened 2021-06-09 07:24 UTC
Per Chethans report on Slack. He spotted missing links in the following pages:
- [Bitcoin backups](https://bitcoin.design/guide/private-key-management/backups/)
- [Funding a wallet](https://bitcoin.design/guide/onboarding/funding-a-wallet/)

**Comment by Bosch-0** [comment] 2021-06-09 07:37
Some others I found with a quick look: 

- Should [sending bitcoin](https://bitcoin.design/guide/payments/send/) have a link to the sub [coin selection](https://bitcoin.design/guide/payments/send/coin-selection/) page? It currently does not. 
- [Coin selection](https://bitcoin.design/guide/payments/send/coin-selection/) missing link to next page.
- [Transaction privacy](https://bitcoin.design/guide/payments/privacy/) missing link to next page.
- Should case study pages link to the next case study? Currently none do.
- [Review](https://bitcoin.design/guide/contribute/review/) page missing link to next page
- [Content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/) missing link to next page 
- [Formatting](https://bitcoin.design/guide/contribute/formatting/) does not link to a next page - maybe link to glossary?

**Comment by paulosacramento** [comment] 2021-06-09 17:04
After taking a look at the first two mentioned pages, I will check the whole guide to see if I find any pages other pages that don't have a link to the next one.

**Comment by paulosacramento** [comment] 2021-06-09 18:01
> Some others I found with a quick look:
> 
> * Should [sending bitcoin](https://bitcoin.design/guide/payments/send/) have a link to the sub [coin selection](https://bitcoin.design/guide/payments/send/coin-selection/) page? It currently does not.
> * [Coin selection](https://bitcoin.design/guide/payments/send/coin-selection/) missing link to next page.
> * [Transaction privacy](https://bitcoin.design/guide/payments/privacy/) missing link to next page.
> * Should case study pages link to the next case study? Currently none do.
> * [Review](https://bitcoin.design/guide/contribute/review/) page missing link to next page
> * [Content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/) missing link to next page
> * [Formatting](https://bitcoin.design/guide/contribute/formatting/) does not link to a next page - maybe link to glossary?

Excellent findings, @Bosch-0 

How can we proceed people?

**Comment by johnsBeharry** [comment] 2021-06-10 09:18
I'm not so sure if these pages in "Contribute to guide" need to have next page links. Similarly to case studies are people going to be going through them linearly or going to specific ones when they need / as they explore.

- Review
- Content guidelines
- Formatting

**Comment by paulosacramento** [comment] 2021-06-10 09:38
> I'm not so sure if these pages in "Contribute to guide" need to have next page links. It's not necessarily ordered by progression. Similarly to case studies are people going to be going through them linearly or going to specific ones when they need / as they explore.
> 
> * Review
> * Content guidelines
> * Formatting

Excellent point. I was thinking about the same thing.

I created these last pull requests because the issue is called 'Ensure **all** pages link to the next page or chapter'.

What do you guys think? @Bosch-0 @GBKS

**Comment by GBKS** [comment] 2021-06-10 11:18
So overall, the idea with these sentence-based links to the next page is to provide a connection between the content of the pages. "Let's go to the next page" is not so great, better is "Now that you know how to propose changes, let's move on to how the review process works". This summarizes what I just read and gives me a connection to what's next. I think something similar can be done between chapters, it just requires a little bit of copy writing.

Another big reason for these links is the fact that you have no other navigation visible on mobile. So I do think they make sense at the end of chapters. It provides some direction as to how we intended the guide to be read and users then don't have to expand the main nav, figure out where they are, decide what's next...

**Comment by pavlenex** [comment] 2021-06-14 09:50
Considering the #393 #394 #395 do we mark this issue as resolved and close it?

This issue is in a way also related to #372.

**Comment by GBKS** [comment] 2021-06-28 12:34
I think we wrap this one up, right?

**Closed** 2021-06-28 12:39 UTC
Labels: copy, good first issue, help wanted
